### ISSUE TITLE
Device Repo Website - Phase 2

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#211]
#### Summary

Phase 2 of design repository will make it more than a list of products, make it easier to find a device using search, breadcrumbs and filters, enhance SEO with more tags and descriptions and add extra product details so this can be more useful while manually adding products via the console or cli.

If we get to it we also want to include integration and webhooks so users can use this to fake devices while developing platforms

#### Why do we need this?

The initial release is laking features and could be improve visually.

#### What is already there? What do you see now?

MVP

#### What is missing? What do you want to see?

See issu

#### How do you propose to implement this?

- [ ] Improve vendor overview https://github.com/TheThingsNetwork/lorawan-devices/issues/190
- [ ] Add tag descriptions https://github.com/TheThingsNetwork/lorawan-devices/issues/185
- [ ] Add device index https://github.com/TheThingsNetwork/lorawan-devices/issues/187
- [x] Add contact TTI form https://github.com/TheThingsNetwork/lorawan-devices/issues/193
- [ ] Add device repository homepage https://github.com/TheThingsNetwork/lorawan-devices/issues/188
- [ ] Add search https://github.com/TheThingsNetwork/lorawan-devices/issues/189
- [ ] Improve single device https://github.com/TheThingsNetwork/lorawan-devices/issues/191
- [ ] Improve device list https://github.com/TheThingsNetwork/lorawan-devices/issues/192
- [ ] How to Add your products https://github.com/TheThingsNetwork/lorawan-devices/issues/205
- [ ] Add breadcrumbs  https://github.com/TheThingsNetwork/lorawan-devices/issues/198

#### Can you do this yourself and submit a Pull Request?

yes, @pierrephz  designs required

**Comment by laurensslats** [comment]
To do: plan design sync with @pierrephz, @mjamescompton & @laurensslats

**Comment by rish-c** [comment]
- [ ] Add contact us form on every product similar to the current marketplace
